config/routes.rb
Rails.application.routes.draw do
  root to: "options#index"

  resources :questions
end

app/models/answer.rb
class Option < ActiveRecord::Base
  has_many :answer
  validates :text, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :option
  validates :text, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def index
    @options = Option.all.order(created_at: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for [@option] do |f| %>
  <div class="form-group">
    <%= f.label "Answer A" %>
    <%= f.text_field :text, class: "form-control" %>
    <%= f.label "Answer B" %>
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <%= question_form.fields_for :option do |option_fields| %>
  <%= option_fields.text_field :text %>
  <% end %>

  <%= f.submit "Submit", class: "btn btn-default center-block" %>
<% end %>

app/views/questions/index.html.erb
<h1>Welcome to "Would You Rather...?"</h1>

<% if @options.any? %>
  <% @options.each do |option| %>
    <div class="container-fluid">
      <h3>Would you rather...</h3>
      <% options.each do |option| %>
        <div class="container-fluid">
          <%= option.text %>
        </div>
        <% end %>
    <% end %>
  <% end %>
<%= link_to "Add Question", new_question_path %>

</div>